// Recipe Data
const recipes = [
    {
        id: 1,
        title: "Authentic Carbonara",
        image: "https://images.pexels.com/photos/461198/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=600",
        cookTime: "20 minutes",
        serving: 4,
        difficulty: "Medium",
        description: "A classic Roman pasta dish with eggs, cheese, pancetta, and black pepper. This traditional recipe has been down through generations and represents the heart of Italian cuisine.",
        ingredients: [
            "400g spaghetti",
            "200g pancetta or guanciale",
            "4 large eggs",
            "100g Pecorino Romano cheese, grated",
            "Freshly ground black pepper",
            "Salt for pasta water",
        ],
        instructions: [
            "Bring a large pot of salted water to boil and cook spaghetti until al dente according to package directions.",
            "Meanwhile, cut pancetta into small cubes and cook in a large pan over medium heat until crispy and golden.",
            "In a bowl, whisk together eggs, grated cheese, and plenty of freshly ground black pepper.",
            "Drain pasta, reserving 1 cup of the starchy pasta cooking water.",
            "Add the hot pasta to the pan with pancetta and toss to combine, removing from heat.",
            "Quickly stir in egg mixture, adding pasta water gradually until creamy and smooth.",
            "Serve immediately with extra cheese and black pepper on top.",
        ],
    },
    {
        id: 2,
        title: "Classic Margherita Pizza",
        image: "https://images.pixels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=800",
        cookTime: "45 mins",
        servings: 2,
        difficulty: "Easy",
        description: "Classic Neapolitan pizza with tomato sauce, fresh mozzarella, and basil. Named after Queen Margherita, this pizza represents the colors of the italian flag.",
        ingredients: [
            "1 ball of pizza dough (homemade or store-bought)",
            "400g crushed San Marzano tomatoes",
            "250g fresh mozzarella di bufala, torn",
            "Fresh basil leaves",
            "Extra virgin olive oil",
            "Sea salt and freshly ground pepper",
            "2 garlic cloves, minced"
        ],
        instructions: [
            "Preheat your oven to its highest setiing (usually 500°F/260°C) with a pizza stone if available.",
            "Roll out pizza dough on a floured surface to your desired thickness.",
            "Mix crushed tomatoes with minced garlic, salt, and pepper for the sauce.",
            "Spread tomato sauce evenly over the dough, leaving a 1-inch border for the crust.",
            "Add torn mozzarella pieces evenly across the pizza and drizzle with olive oil.",
            "Bake for 10-12 minutes until the crust is golden and the cheese is bubbly with brown spots.",
            "Remove from oven and immediately top with fresh basil leaves before serving."
        ]
    },
    {
        id: 3,
        title: "Classic Tiramisu",
        image: "https://images.pexels.com/photos/6368370/pexels-photo-6368370.jpeg?auto=compress&cs=tinysrgb&w=800",
        cookTime: "30 mins",
        servings: 8,
        difficulty: "Medium",
        description: "The iconic Italian dessert with coffee-soaked ladyfingers layered with a rich mascarpone cream. Tiramisu means 'pick me up' in Italian, and this dessert certainly lives up to its name.",
        ingredients: [
            "6 large egg yolks",
            "3/4 cup granulated sugar",
            "500g mascarpone cheese, room temperature",
            "1.5 cups strong espresso, cooled",
            "3 tablespoons coffee liqueur (optional)",
            "30 ladyfingers (savoiardi)",
            "Unsweetened cocoa powder for dusting",
            "Dark chocolate shavings for garnish", 
        ],
        instructions: [
            "Whisk egg yolks and sugar in a double boiler over simmering water until thick, pale, and ribbonny.",
            "Remove from heat and whisk in mascarpone until completely smooth. Let cool to room temperature.",
            "Combine cooled espresso and coffee liquer in a shallow dish.",
            "Quickly dip each ladyfinger in the coffee mixture and arrange in a single layer in your dish.",
            "Spread half of the mascarpone mixture over the ladyfingers, smoothing it out evenly.",
            "Repeat with another layer of dipped ladyfingers and the remaining mascarpone mixture.",
            "Cover and refrigerate for at least 4 hours or overnight for best results.",
            "Before serving, dust generously with cocoa powder and garnish with dark chocolate shavings.",
        ]
    },
    {
        id: 4,
        title: "Risotto alla Milanese",
        image: "https://images.pexels.com/photos/8601236/pexels-photo-8601236.jpeg?auto=compress&cs=tinysrgb&w=800",
        cookTime: "35 mins",
        servings: 4,
        difficulty: "Hard",
        description: "Creamy saffron risotto form Milan, golden in color and rich in flavor. This luxurious dish requires patience and technique but rewards with incredible taste.",
        ingredients: [
            "320g Arborio rice",
            "1.5L warm chicken or vegetable stock",
            "1/2 cup dry while wine",
            "1 large onion, finely chopped",
            "3 tablespons butter",
            "2 tablespoons olive oil",
            "Pinch of saffron threads",
            "100g Parmigiano-Reggiano, grated",
            "Salt and white pepper to taste",
        ],
        instructions: [
            "Heat the stock in a saucepan and keep it warm. Steep saffron in 2 tablespoons of hot stock.",
            "Heat olive oil and 1 tablespoon butter in a heavy-bottomed pan over medium heat.",
            "Add chopped onion and cook until translucent, about 5 minutes.",
            "Add rice and stir for 2 minutes until grains are well-coated and slightly translucent.",
            "Pour in wine and stir until absorbed completely.",
            "Add warm shock one lable at a time, stirring constantly until absorbed before adding more.",
            "After about 15 minutes, add the safron mixture and continue adding stock until rice is creamy but al dente.",
            "Remove from heat, stir in remaining butter and Parmigiano-Reggiano. Season and serve immediately.",
        ]
    },
    {
        id: 5,
        title: "Osso Buco",
        image: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=800",
        cookTime: "2.5 hours",
        servings: 6,
        difficulty: "Hard",
        description :"Slow-braised veal shanks in a rich tomato and wine sauce. This Milanese speciality is comfort food at its finest, perfect for special occasions.",
        ingredients: [
            "6 veal shanks, about 2 inches thick",
            "1/2 cup all-purpose flour",
            "4 tablespoons olive oil",
            "1 large onion, diced",
            "2 carrots, diced",
            "2 celery stalks, diced",
            "4 garlic cloves, minced",
            "1 cup dry white wine",
            "1 can (400g) diced tomatoes",
            "2 cups beef or veal stock",
            "2 bay leaves",
            "Fresh thyme and rosemary sprigs",
            "Gremolata (chopped parsley, lemon zest, and garlic) for garnish",
        ],
        instructions: [
            "Preheat oven to 350°F (165°C). Season veal shanks and dredge in flour, shaking off excess.",
            "Heat olive oil in a large Dutch oven and brown veal shanks on all sides. Remove and set aside.",
            "In the same pot, sauté onion, carrots, celery, and garlic until softened for about 8 minutes.",
            "Add garlic and cook for another minute until fragrant.",
            "Pour in wine to deglaze, scrapiing up any browned bits from the bottom.",
            "Add tomatoes, stock, herbs, and return veal to the pot.",
            "Cover and braise in the oven for 2-2.5 hours until meat is fork-tender.",
            "Prepare gremolata by mixing lemon zest, minced garlic, and chopped parsely.",
            "Serve osso buco with gremolata and traditional risotto alla milanese.",
        ]
    },
    {
        id: 6,
        title: "Panna Cotta",
        image: "https://images.pexels.com/photos/4099123/pexels-photo-4099123.jpeg?auto=compress&cs=tinysrgb&w=800",
        cookTime: "25 mins",
        servings: 6,
        difficulty: "Easy",
        description: "Silky smooth vanilla custard dessert that melts in your mouth. This elegant dessert is surprisingly simple to make and always impresses guests.",
        ingredients: [
            "2 cups heavy cream",
            "1/2 cup granulated sugar",
            "1 packet (2.25 tsp) unflavored gelatin",
            "3 tablespoon water",
            "1 vanilla bean or 1 teaspoon vanilla extract", 
            "Pinch of salt",
            "Fresh berries or berry sauce for serving",
            "Berry coulis or caramel sauce for drizzling",
        ],
        instructions: [
            "Sprinkle gelatin over cold water in a small bowl and let bloom for 5 minutes.",
            "Split vanilla bean and scrape seeds into cream, or add vanilla extract.",
            "Heat cream, sugar, vanilla, and salt in a saucepan until sugar dissolves and mixture is hot but not boiling.",
            "Remove from heat and whisk in the bloomed gelatin until completely dissolved.",
            "Strain mixture through a fine sieve into a measuring jug to remove any lumps.",
            "Dvide among 6 ramekins or glasses and refrigirate for at least 4 hours or until set.",
            "Serve chilled with fresh berries and a drizzle of berry coulis or caramel sauce.",
            "To unmold, briefly dip ramekins in warm water and invert onto plates.",
        ]
    }
];

// Menu data
const menuItems = [
    {
        id: 1,
        name: "Bruschetta Italiana",
        description: "Grilled artisan bread topped with fresh tomatoes, basil, garlic, and extra virgin olive oil",
        price: "$12",
        image: "https://images.pexels.com/photos/5755889/pexels-photo-5755889.jpeg?auto=compress&cs=tinysrgb&w=600",
        category: "appetizers"
    },
    {
        id: 2,
        name: "Antipasto Della Casa",
        description: "Chef's selection of cured meats, artisanal cheeses, olives, and marinated vegetables",
    }
]